# Generated by Django 4.1.4 on 2023-03-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('therauptic_category', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
