# Generated by Django 4.1.4 on 2023-03-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_dosage_medicine_image_medicine_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='ballot_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='raksha_value',
            field=models.IntegerField(default=0),
        ),
    ]
