# Generated by Django 4.0.6 on 2023-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleregistration',
            name='email',
            field=models.CharField(default='abc@gmail.com', max_length=100),
        ),
    ]
