# Generated by Django 4.0.6 on 2023-03-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_roleregistration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleregistration',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='roleregistration',
            name='role',
        ),
        migrations.AlterField(
            model_name='roleregistration',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
